### ISSUE TITLE
Edit Post - submit failed

### ISSUE THREAD

**Issue by YoshieFujiwara** [lan-solo-capstone/freeshare#186]
Heroku app

1. created a new user and created a new post - saved successfully as expected
2. Hit edit item - changed item condition.  Hit submit
3. Toast notification triggered as successful at first, then triggered second yellow notification communicating something went wrong.  
4.  Cancelled the item and clicked to re-edit.  I am seeing the changed item condition so data seems to have been saved - is this false negative?

**Comment by YoshieFujiwara** [comment]
Not seeing the obvious errors in the browser - may be a failure from server, which I could not check from heroku.
userName : cody@thePug.com
item name: Free sourdough starter

**Comment by jaechung80** [comment]
Closed: authenticated via ensureLogin and not ensureAdmin
