### ISSUE TITLE
If user never had message history, it shows 'Loading....' on the page

### ISSUE THREAD

**Issue by YoshieFujiwara** [lan-solo-capstone/freeshare#189]
I have a user who never used chat feature.   Since there is "Messages" link in profile page, I clicked on it - it shows just Loading.. message.

<img width="1040" alt="Screen Shot 2021-04-01 at 4 01 00 PM" src="https://user-images.githubusercontent.com/52583394/113353579-84f89280-9303-11eb-852a-e95b24176dec.png">

**Comment by YoshieFujiwara** [comment]
Okay, there is a different way to get to message - https://free-share-capstone.herokuapp.com/messages/all
This page is showing nice display - can we replace this view to above page?

<img width="1407" alt="Screen Shot 2021-04-01 at 4 16 14 PM" src="https://user-images.githubusercontent.com/52583394/113354940-9b9fe900-9305-11eb-8ee0-74dfe4c785a0.png">

**Comment by jaechung80** [comment]
look into InboxContainer user.id undefined
