### ISSUE TITLE
User Profile - Styling & add "Home" to bring users back to the main browse items page? ( Only web browser)

### ISSUE THREAD

**Issue by YoshieFujiwara** [lan-solo-capstone/freeshare#191]
Not sure if we have any way to help users to know how to move out from the Edit Profile page - navbar is the only option to navigate out from this page.  It may not be intuitive for the users to reply navbar to go back.   Would be nice if there is a link or button for users to go back to the main page.   I don't think this will be an issue in mobile as there is home buttom. 

Also, can we address stylying?  Need some div/space between navbar and heading horizontal row:

 
<img width="1072" alt="Screen Shot 2021-04-01 at 4 11 47 PM" src="https://user-images.githubusercontent.com/52583394/113354780-4c59b880-9305-11eb-8755-572340becd93.png">

**Comment by MelindaJoArmbruster** [comment]
Users already have two options on the navbar for returning to the list all view page. Since this is only a concern in desktop view, the navbar would be expected to be visible. Today's users can navigate a typical navbar. I did address styling this evening.
