### ISSUE TITLE
User Profile < Message - styling

### ISSUE THREAD

**Issue by YoshieFujiwara** [lan-solo-capstone/freeshare#192]
https://free-share-capstone.herokuapp.com/messages/all

Notice how the navbar and top content area merge.

<img width="994" alt="Screen Shot 2021-04-01 at 4 19 28 PM" src="https://user-images.githubusercontent.com/52583394/113355276-21bc2f80-9306-11eb-99b4-aea0aad12de7.png">

**Comment by MelindaJoArmbruster** [comment]
This is actually not related to user profile. I added margin to the top of InboxOnly to address this.
