### ISSUE TITLE
Styling on New Item Form

### ISSUE THREAD

**Issue by jaechung80** [lan-solo-capstone/freeshare#199]
1. Right now it says "Example description... Ipsum loram". Delete "Ipsum loram" and/or put something that resembles a real item description
2. Increase (or make consistent) line spacing between text elements (Item Name is really close to dropdown above it, for example)
3. Capitalization is inconsistent in Choose Files: no files selected. This may be annoying to fix but this StackOverflow has some suggestions: https://stackoverflow.com/questions/16001586/change-the-no-file-chosen

**Comment by diego-abreu** [comment]
PR #222 hit 1 and 2 although 3 isn't possible because bootstrap manages it
