### ISSUE TITLE
Talk JS - Reminder to go live with Talk JS

### ISSUE THREAD

**Issue by YoshieFujiwara** [lan-solo-capstone/freeshare#207]
Not sure if this is what we are planning to do, but wanted to document - currently, message/talk.js is showing a message indicating it is running as a test mode.

<img width="1208" alt="Screen Shot 2021-04-01 at 11 44 24 PM" src="https://user-images.githubusercontent.com/52583394/113381439-99a94a80-9344-11eb-9bd0-ffc91abe1bd8.png">

**Comment by YoshieFujiwara** [comment]
Assigning to Jae for review.

**Comment by jaechung80** [comment]
Won't do this as it would cost $270 per month
