### ISSUE TITLE
New User Sign Up - can we trigger "User Already exists " message after entering an email address?

### ISSUE THREAD

**Issue by YoshieFujiwara** [lan-solo-capstone/freeshare#209]
When the user is trying to create the account already in the user table, the app triggers an error message.   I am wondering if we can trigger it after entering the email id, instead of allowing users to enter all the forms and hit the sign-up button for better UX.    This is an enhancement and not a show-stopper.

<img width="1363" alt="Screen Shot 2021-04-02 at 12 00 19 AM" src="https://user-images.githubusercontent.com/52583394/113382268-b6468200-9346-11eb-9448-e5f20627451f.png">

**Comment by YoshieFujiwara** [comment]
Not worth working on this if there is a risk of breaking the functionality - just wanted to document my observation.

**Comment by MelindaJoArmbruster** [comment]
The validation is triggered when the user hits submit. I don't think it's worth rewriting this.
