### ISSUE TITLE
New User Sign-Up - "This user already exist" error can be cancelled out, then user get stuck on page.  Critical error reappear in Log-in form

### ISSUE THREAD

**Issue by YoshieFujiwara** [lan-solo-capstone/freeshare#210]
When the user entered the email address that is already on file, it triggers a critical error ( expected), which you can cancel the message display by hitting X ( strange feature - I expect the user to not be able to visually remove the error).   Once the user removed the error, the user gets stuck on the page due to the behind-the-scene auth 401 error.  

Can we do something about X on the critical error? Please refer to my comment in the below section.

<img width="1363" alt="Screen Shot 2021-04-02 at 12 00 19 AM" src="https://user-images.githubusercontent.com/52583394/113382676-b6934d00-9347-11eb-95c5-7148c04df5ea.png">
<img width="1241" alt="Screen Shot 2021-04-02 at 12 11 29 AM" src="https://user-images.githubusercontent.com/52583394/113382783-fe19d900-9347-11eb-8697-a0813a0a74c9.png">

**Comment by YoshieFujiwara** [comment]
If we can disable the X on critical error, that would force user to click on LogIn.   Seems obvious, but any reason you remove the error, it is a puzzling user experience.

**Comment by YoshieFujiwara** [comment]
Ok,  more observation - if you click on "LogIn" link, the overlay box refreshes to show only email and password, but the User Already Exist message is showing up again.

Steps to replicate 
1) enter new user form as existing user - observe the "user already exist" message
2) click on Log in link next to "Already Registered?"

<img width="1237" alt="Screen Shot 2021-04-02 at 12 14 19 AM" src="https://user-images.githubusercontent.com/52583394/113382998-84361f80-9348-11eb-90ce-a766a4ee0672.png">

**Comment by MelindaJoArmbruster** [comment]
I recreated the "user already exists" error then clicked log in without closing the pink error message and, of course, the error message persisted to the log in page. But, it goes away when the user clicks the X to close it, from any view. Not sure what other behavior we expect here.
