### ISSUE TITLE
iPhone - create new item - when selecting photos, app does not allow me to submit the item

### ISSUE THREAD

**Issue by YoshieFujiwara** [lan-solo-capstone/freeshare#216]
I selected photos from my photo libraries to create a new item - it selects and allows me to preview my photos as expected.  I can also check off and unselect pictures before submitting the form as expected. 

However, it does not allow me to submit the item.

As soon as I remove the photo attachment, the request submits completes.
Also, if using the camera to take pictures and attach the picture, the form gets submitted.

In general - submit button behaves slowly so it gives an impression that submits has failed - then a bit later you see toast notifications.   

I am experiencing this issue in chrome and safari

**Comment by YoshieFujiwara** [comment]
Ok, this is weird - when i hit the "submit" , no toast notification triggered but now I am seeing bunch items created ( probably representing submits I pressed to test it around) with 1 photo.   Looks like it is creating an item with a photo -  bur it show in delay.   This needs more observation - assigning to myself for now.

**Comment by YoshieFujiwara** [comment]
I have made several more testing and updated the description - please refer to the above.

**Comment by jaechung80** [comment]
Will not address before demo day

**Comment by YoshieFujiwara** [comment]
multer was suggested as it handles photo resizing - I have seen a mentioning on photo sizing management tool inside of firebase or part of the library code.   I want to revisit my old research to see if there is any solutions applicable to address this issue - not committed to fix this before the demo, but I am now curious.
