### ISSUE TITLE
Google Authentication - hitting error

### ISSUE THREAD

**Issue by YoshieFujiwara** [lan-solo-capstone/freeshare#221]
I have used my own google account to log in.    It directed me to the Google authentication page for the first time and asking my permission to access to freeshare application (expected).   I validated there, and upon redirecting me back to the freeshare app, app returned me with an authentication error.   This is seeing in both the web and phone. 

fyi - created google test account
/*
freeshare testAccount

freesharetest@gmail.com
password: freeshare12345!
*/

You hit validation error first, then hit bad request next. ( see pics below)

<img width="718" alt="Screen Shot 2021-04-02 at 6 10 22 AM" src="https://user-images.githubusercontent.com/52583394/113411023-68e40800-937a-11eb-8936-2a37d2ea75b7.png">
<img width="726" alt="Screen Shot 2021-04-02 at 6 09 49 AM" src="https://user-images.githubusercontent.com/52583394/113411025-6b466200-937a-11eb-9c4b-a4a0a92b2b3d.png">

[from console]
Request URL: https://free-share-capstone.herokuapp.com/auth/google/callback?code=4%2F0AY0e-g44Ihjz6tGDybdiipqjEciP1mZLKYznafRGTW9B8FMwJ2aQxR6hqMuu-KG0gjvP_A&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=0&prompt=none
Request Method: GET
Status Code: 500 Internal Server Error (from service worker)
Referrer Policy: strict-origin-when-cross-origin

Connection: keep-alive
Content-Length: 16
Content-Type: text/html; charset=utf-8
Date: Fri, 02 Apr 2021 11:10:09 GMT
Etag: W/"10-4VfNCnahTYgYXA85bTZcHBL2o08"
Server: Cowboy
Vary: Accept-Encoding
Via: 1.1 vegur
X-Powered-By: Express
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Cookie: connect.sid=s%3A5XDpPK0NLD56rQ8gkLCsRYlVZZug4He4.PhmR%2BFtSprpIkREhfnSEszv%2FDrJdk2CbiqiMl3a8Wzc; io=DeuyXfxtOTzJgrBGAACj
Host: free-share-capstone.herokuapp.com
Referer: https://free-share-capstone.herokuapp.com/
sec-ch-ua: "Chromium";v="88", "Google Chrome";v="88", ";Not A Brand";v="99"
sec-ch-ua-mobile: ?0
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Service-Worker-Navigation-Preload: true
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
X-Chrome-Connected: source=Chrome,mode=0,enable_account_consistency=false,supervised=false,consistency_enabled_by_default=false
X-Chrome-ID-Consistency-Request: version=1,client_id=77185425430.apps.googleusercontent.com,device_id=1a75daec-058f-46c0-88d4-00319ebbcce5,sync_account_id=100336361687747157918,signin_mode=all_accounts,signout_mode=show_confirmation
X-Client-Data: CJK2yQEIpLbJAQjEtskBCKmdygEI+MfKAQijzcoBCM3PygEI3NXKAQjNmssBCKecywEIxpzLAQjknMsBCKmdywE=
Decoded:
message ClientVariations {
  // Active client experiment variation IDs.
  repeated int32 variation_id = [3300114, 3300132, 3300164, 3313321, 3318776, 3319459, 3319757, 3320540, 3329357, 3329575, 3329606, 3329636, 3329705];
}
code: 4/0AY0e-g44Ihjz6tGDybdiipqjEciP1mZLKYznafRGTW9B8FMwJ2aQxR6hqMuu-KG0gjvP_A
scope: email profile openid https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
authuser: 0
prompt: none

**Comment by YoshieFujiwara** [comment]
I created an account first without using "sign-up" with google - then tried to log in with google.

FYI - auth/google is not showing google auth page anymore - and clicking on login with google or signup with google keeps redirecting me back to this view.   This is from local - i can not replicate google error above from local as it behaves differently ( probably expected as you can only connect the google auth stuff to production?)

<img width="1215" alt="Screen Shot 2021-04-02 at 6 18 03 AM" src="https://user-images.githubusercontent.com/52583394/113411408-456d8d00-937b-11eb-8db8-3e751ba6dec5.png">

**Comment by MelindaJoArmbruster** [comment]
Let's go over the auth stuff when we are able to get together today.

**Comment by jaechung80** [comment]
Not a bug! =)
